apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - post-sync-smoketests.yaml
  - virtual-service.yaml
commonLabels:
  app: notebook
configMapGenerator:
  - name: notebook-config
    literals:
      - PORT=8000

