apiVersion: batch/v1
kind: Job
metadata:
  name: notebook-smoketests
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        # command: ["grep", "asdf"]
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
