apiVersion: batch/v1
kind: Job
metadata:
  name: notebook-promote
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
    sidecar.istio.io/inject: "false"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: sleep
        image: curlimages/curl:latest
        command:
          - curl
          - -XPOST
          - "-u $(DEPLOY_USERNAME):$(DEPLOY_TOKEN)"
          - "-H \"Accept: application/vnd.github.everest-preview+json\""
          - "-H \"Content-Type: application/json\""
          - -v
          - https://api.github.com/repos/jasonblanchard/k8s-pipeline-testing-deploy/dispatches
          - --data
          - '{"event_type": "deploy", "client_payload": { "version": "$(VERSION)", "service": "notebook", "environment": "production" }}'
        env:
          - name: VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['version']
          - name: DEPLOY_TOKEN
            valueFrom:
              secretKeyRef:
                name: deploy-token
                key: token
          - name: DEPLOY_USERNAME
            valueFrom:
              secretKeyRef:
                name: deploy-token
                key: username
      restartPolicy: Never
  backoffLimit: 0
