apiVersion: batch/v1
kind: Job
metadata:
  name: notebook-promote
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: sleep
        image: curlimages/curl:latest
        # command: ["/bin/sh", "-c"]
        # args: ["curl", "-XPOST -u \"$DEPLOY_USER:$DEPLOY_TOKEN\" -H \"Accept: application/vnd.github.everest-preview+json\" -H \"Content-Type: application/json\" https://api.github.com/repos/jasonblanchard/k8s-pipeline-testing-deploy/dispatches --data '{\"event_type\": \"deploy\", \"client_payload\": { \"version\": \"$VERSION\", \"service\": \"notebook\", \"environment\": \"production\"} }'"]
        args:
          - -XPOST -u "$DEPLOY_USER:$DEPLOY_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/jasonblanchard/k8s-pipeline-testing-deploy/dispatches --data '{"event_type": "deploy", "client_payload": { "version": "$VERSION", "service": "notebook", "environment": "production"} }'
          # - localhost
        env:
          - name: VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['version']
          - name: DEPLOY_TOKEN
            valueFrom:
              secretKeyRef:
                name: deploy-token
                key: token
          - name: DEPLOY_TOKEN
            valueFrom:
              secretKeyRef:
                name: deploy-token
                key: user
      restartPolicy: Never
  backoffLimit: 0
