apiVersion: batch/v1
kind: Job
metadata:
  name: notebook-promote
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: sleep
        # image: curlimages/curl:latest
        image: ubuntu:latest
        # command: ["bash", "-c", "echo", "$VERSION"]
        command: ["printenv"]
        env:
          - name: VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['version']
      restartPolicy: Never
  backoffLimit: 0
